import { ExpenseItem, BillAccount } from '../types';

/**
 * Returns the number of days in a given year and month (0-indexed).
 */
export function getDaysInMonth(year: number, monthZeroIndexed: number): number {
  return new Date(year, monthZeroIndexed + 1, 0).getDate();
}

/**
 * Clamps a day of the month (1-31) to the actual maximum days in the given month.
 */
export function clampDayToMonth(year: number, monthZeroIndexed: number, desiredDay: number): number {
  const maxDays = getDaysInMonth(year, monthZeroIndexed);
  return Math.min(Math.max(1, desiredDay), maxDays);
}

/**
 * Formats a Date into YYYY-MM-DD string with local date safety.
 */
export function formatDateKey(year: number, monthZeroIndexed: number, day: number): string {
  const y = year.toString().padStart(4, '0');
  const m = (monthZeroIndexed + 1).toString().padStart(2, '0');
  const d = day.toString().padStart(2, '0');
  return `${y}-${m}-${d}`;
}

/**
 * Generates an array of formatted upcoming dates for a given monthly recurring day.
 * e.g., Day 17 -> ["17 Oct 2026", "17 Nov 2026", "17 Dec 2026"]
 */
export function getUpcomingRecurringDates(
  dayOfMonth: number,
  count: number = 3,
  referenceDate: Date = new Date()
): string[] {
  const results: string[] = [];
  const currentYear = referenceDate.getFullYear();
  const currentMonth = referenceDate.getMonth();
  const currentDay = referenceDate.getDate();

  // If today hasn't passed the recurring day yet this month, start with current month;
  // otherwise start next month.
  let startOffset = currentDay < dayOfMonth ? 0 : 1;

  for (let i = 0; i < count; i++) {
    const targetMonthIndex = currentMonth + startOffset + i;
    const targetDateObj = new Date(currentYear, targetMonthIndex, 1);
    const y = targetDateObj.getFullYear();
    const m = targetDateObj.getMonth();
    const clampedDay = clampDayToMonth(y, m, dayOfMonth);
    const date = new Date(y, m, clampedDay);

    results.push(
      date.toLocaleDateString('en-MY', {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
      })
    );
  }

  return results;
}

/**
 * Creates a new child expense entry for a given recurring parent on a specific target date (YYYY-MM-DD).
 */
export function createRecurringExpenseEntry(
  parent: ExpenseItem,
  targetDateStr: string
): ExpenseItem {
  const seriesId = parent.recurringSeriesId || parent.id;
  const uniqueSuffix = Math.random().toString(36).slice(2, 7);
  const newId = `exp-rec-${Date.now()}-${uniqueSuffix}`;

  const isDuitNowOrCash = parent.paymentMode === 'duitnow_qr' || parent.paymentMode === 'cash';
  const shouldSettle = isDuitNowOrCash || parent.status === 'settled';

  // Format month and year label for notes
  const [yearStr, monthStr] = targetDateStr.split('-');
  const monthDate = new Date(parseInt(yearStr, 10), parseInt(monthStr, 10) - 1, 1);
  const monthLabel = monthDate.toLocaleDateString('en-MY', { month: 'long', year: 'numeric' });

  // Ensure '#recurring' tag is present
  const tags = parent.tags ? [...parent.tags] : [];
  if (!tags.includes('#recurring')) {
    tags.push('#recurring');
  }

  const newExpense: ExpenseItem = {
    ...parent,
    id: newId,
    date: targetDateStr,
    autoGenerated: true,
    isRecurring: false, // The child is a specific occurrence; parent holds the recurring schedule
    parentRecurringExpenseId: parent.id,
    recurringSeriesId: seriesId,
    status: shouldSettle ? 'settled' : 'unsettled',
    settledAt: shouldSettle ? `${targetDateStr}T09:00:00.000Z` : undefined,
    settlementMethod: shouldSettle ? (parent.settlementMethod || 'instant_fpx') : undefined,
    settlementReference: shouldSettle ? `REC-${Date.now().toString(36).toUpperCase()}` : undefined,
    settledFromAccountId: shouldSettle ? (parent.settledFromAccountId || parent.accountId) : undefined,
    notes: parent.notes 
      ? `${parent.notes} (Monthly recurring bill for ${monthLabel})`
      : `Auto-generated monthly recurring bill for ${monthLabel}`,
    tags,
  };

  return newExpense;
}

/**
 * Checks all recurring expenses and automatically generates any missing monthly entries
 * up to the referenceDate (defaults to current date).
 * 
 * Accurately updates account balances (increases balance on unsettled cards, or deducts from bank if auto-settled).
 */
export function processDueRecurringExpenses(
  expenses: ExpenseItem[],
  accounts: BillAccount[],
  referenceDate: Date = new Date(),
  dismissedRecurringKeys: string[] = [],
  deletedExpenseIds: string[] = []
): {
  updatedExpenses: ExpenseItem[];
  updatedAccounts: BillAccount[];
  generatedCount: number;
  newlyGeneratedExpenses: ExpenseItem[];
} {
  const deletedSet = new Set(deletedExpenseIds);
  const dismissedSet = new Set(dismissedRecurringKeys);

  // Filter out any deleted items immediately
  let nextExpenses = expenses.filter((e) => !deletedSet.has(e.id));
  let nextAccounts = [...accounts];

  const recurringParents = nextExpenses.filter((e) => e.isRecurring && !deletedSet.has(e.id));
  if (recurringParents.length === 0) {
    return {
      updatedExpenses: nextExpenses,
      updatedAccounts: nextAccounts,
      generatedCount: 0,
      newlyGeneratedExpenses: [],
    };
  }

  const newlyGeneratedExpenses: ExpenseItem[] = [];

  const refYear = referenceDate.getFullYear();
  const refMonth = referenceDate.getMonth();
  const refDay = referenceDate.getDate();

  for (const parent of recurringParents) {
    const seriesId = parent.recurringSeriesId || parent.id;
    const parentDateParts = parent.date.split('-');
    const parentYear = parseInt(parentDateParts[0], 10);
    const parentMonth = parseInt(parentDateParts[1], 10) - 1; // 0-indexed
    const parentDay = parseInt(parentDateParts[2], 10);

    const recurringDay = parent.recurringDay || parentDay || 1;

    // Collect all existing (YYYY-MM) keys for this series across all expenses
    const existingMonthKeys = new Set<string>();
    for (const exp of nextExpenses) {
      if (exp.id === parent.id || exp.parentRecurringExpenseId === parent.id || exp.recurringSeriesId === seriesId) {
        const parts = exp.date.split('-');
        if (parts.length >= 2) {
          existingMonthKeys.add(`${parts[0]}-${parts[1]}`);
        }
      }
    }

    // Iterate through months starting from the month AFTER the parent's initial date,
    // up to the reference month
    let curY = parentYear;
    let curM = parentMonth + 1;

    while (curY < refYear || (curY === refYear && curM <= refMonth)) {
      const monthKey = `${curY.toString().padStart(4, '0')}-${(curM + 1).toString().padStart(2, '0')}`;
      const seriesKey = `${seriesId}:${monthKey}`;
      const parentKey = `${parent.id}:${monthKey}`;

      // Check if user previously deleted or dismissed this recurring cycle
      if (dismissedSet.has(seriesKey) || dismissedSet.has(parentKey)) {
        existingMonthKeys.add(monthKey);
        curM++;
        if (curM > 11) {
          curM = 0;
          curY++;
        }
        continue;
      }

      const clampedDay = clampDayToMonth(curY, curM, recurringDay);

      // Check if we have reached or passed the recurring day in this month
      const isPastOrToday = (curY < refYear) || (curY === refYear && curM < refMonth) || (curY === refYear && curM === refMonth && refDay >= clampedDay);

      if (isPastOrToday && !existingMonthKeys.has(monthKey)) {
        const targetDateStr = formatDateKey(curY, curM, clampedDay);
        const newEntry = createRecurringExpenseEntry(parent, targetDateStr);

        if (!deletedSet.has(newEntry.id)) {
          newlyGeneratedExpenses.push(newEntry);
          existingMonthKeys.add(monthKey);

          // Update balances
          if (newEntry.status === 'unsettled') {
            const accIdx = nextAccounts.findIndex((a) => a.id === newEntry.accountId);
            if (accIdx !== -1) {
              nextAccounts[accIdx] = {
                ...nextAccounts[accIdx],
                totalBalance: Math.round((nextAccounts[accIdx].totalBalance + newEntry.amount) * 100) / 100,
              };
            }
          } else if (newEntry.status === 'settled' && newEntry.settledFromAccountId) {
            const bankIdx = nextAccounts.findIndex((a) => a.id === newEntry.settledFromAccountId);
            if (bankIdx !== -1) {
              nextAccounts[bankIdx] = {
                ...nextAccounts[bankIdx],
                totalBalance: Math.max(0, Math.round((nextAccounts[bankIdx].totalBalance - newEntry.amount) * 100) / 100),
              };
            }
          }
        }
      }

      // Step to next month
      curM++;
      if (curM > 11) {
        curM = 0;
        curY++;
      }
    }
  }

  if (newlyGeneratedExpenses.length > 0) {
    // Prepend newly generated items to the front of expenses
    nextExpenses = [...newlyGeneratedExpenses, ...nextExpenses];
  }

  return {
    updatedExpenses: nextExpenses,
    updatedAccounts: nextAccounts,
    generatedCount: newlyGeneratedExpenses.length,
    newlyGeneratedExpenses,
  };
}

/**
 * Manually generates the next monthly cycle for a recurring expense on demand
 * (ideal for immediate testing or advance scheduling in the UI).
 */
export function forceGenerateNextRecurringMonth(
  parentExpense: ExpenseItem,
  allExpenses: ExpenseItem[],
  accounts: BillAccount[]
): {
  newExpense: ExpenseItem;
  updatedExpenses: ExpenseItem[];
  updatedAccounts: BillAccount[];
} {
  const seriesId = parentExpense.recurringSeriesId || parentExpense.id;
  const existingMonthKeys = new Set<string>();

  for (const exp of allExpenses) {
    if (exp.id === parentExpense.id || exp.parentRecurringExpenseId === parentExpense.id || exp.recurringSeriesId === seriesId) {
      const parts = exp.date.split('-');
      if (parts.length >= 2) {
        existingMonthKeys.add(`${parts[0]}-${parts[1]}`);
      }
    }
  }

  const parentDateParts = parentExpense.date.split('-');
  let curY = parseInt(parentDateParts[0], 10);
  let curM = parseInt(parentDateParts[1], 10) - 1;
  const recurringDay = parentExpense.recurringDay || parseInt(parentDateParts[2], 10) || 1;

  // Find next month without an existing entry
  let found = false;
  let targetDateStr = '';

  for (let step = 1; step <= 24; step++) {
    curM++;
    if (curM > 11) {
      curM = 0;
      curY++;
    }
    const monthKey = `${curY.toString().padStart(4, '0')}-${(curM + 1).toString().padStart(2, '0')}`;
    if (!existingMonthKeys.has(monthKey)) {
      const clampedDay = clampDayToMonth(curY, curM, recurringDay);
      targetDateStr = formatDateKey(curY, curM, clampedDay);
      found = true;
      break;
    }
  }

  if (!found) {
    const nextDate = new Date();
    nextDate.setMonth(nextDate.getMonth() + 1);
    const clampedDay = clampDayToMonth(nextDate.getFullYear(), nextDate.getMonth(), recurringDay);
    targetDateStr = formatDateKey(nextDate.getFullYear(), nextDate.getMonth(), clampedDay);
  }

  const newEntry = createRecurringExpenseEntry(parentExpense, targetDateStr);
  const nextExpenses = [newEntry, ...allExpenses];
  let nextAccounts = [...accounts];

  if (newEntry.status === 'unsettled') {
    const accIdx = nextAccounts.findIndex((a) => a.id === newEntry.accountId);
    if (accIdx !== -1) {
      nextAccounts[accIdx] = {
        ...nextAccounts[accIdx],
        totalBalance: Math.round((nextAccounts[accIdx].totalBalance + newEntry.amount) * 100) / 100,
      };
    }
  } else if (newEntry.status === 'settled' && newEntry.settledFromAccountId) {
    const bankIdx = nextAccounts.findIndex((a) => a.id === newEntry.settledFromAccountId);
    if (bankIdx !== -1) {
      nextAccounts[bankIdx] = {
        ...nextAccounts[bankIdx],
        totalBalance: Math.max(0, Math.round((nextAccounts[bankIdx].totalBalance - newEntry.amount) * 100) / 100),
      };
    }
  }

  return {
    newExpense: newEntry,
    updatedExpenses: nextExpenses,
    updatedAccounts: nextAccounts,
  };
}
